#!/bin/bash

export PROJECT_ROOT=~/AdaptPolicies
export PATH=$CONDA_PREFIX/bin:$PATH
export VIRTUALHOME_PREFIX=$PROJECT_ROOT/src/virtual_home
export VIRTUALHOME_DIR=$VIRTUALHOME_PREFIX/virtualhome
export VIRTUALHOME_ROOT=$VIRTUALHOME_DIR/src/virtualhome
export PYTHONPATH=${PROJECT_ROOT}/src:${VIRTUALHOME_PREFIX}:${VIRTUALHOME_ROOT}:${VIRTUALHOME_ROOT}/simulation
export LIBGL_ALWAYS_INDIRECT=0
export OLLAMA_HOST=http://localhost:11430
export VIRTUALHOME_SIM_VERSION=v2.0/v2.3.0
export SIM_PORT=8082
