#!/bin/bash

export PATH=$(echo $PATH | sed -e "s|$CONDA_PREFIX/bin:||g")
unset PROJECT_ROOT
unset PYTHONPATH
unset LIBGL_ALWAYS_INDIRECT
unset OLLAMA_HOST
unset VIRTUALHOME_PREFIX
unset VIRTUALHOME_DIR
unset VIRTUALHOME_SIM_VERSION
unset VIRTUALHOME_ROOT
unset SIM_PORT
